### ISSUE TITLE
Browser version?

### ISSUE THREAD

**Issue by iapon** [antonmedv/finder#19]
Is there bundled browser version?

**Comment by antonmedv** [comment]
You can use https://unpkg.com/@medv/finder

**Comment by iapon** [comment]
> You can use https://unpkg.com/@medv/finder

Looks like it wants cssesc to work?
Also, did you want to add multi-selectors as input in the future(for getting the path for all of them)?

**Comment by iapon** [comment]
> AA, no bundled version =)
> You can add pr for bundled version if you want. For example I'll save it to releases page.
> multi-selectors? What not just call finder a few times?

Sorry, I'm not so familiar with .ts, modules, bundling and etc.
About multi-selectors I mean, for example, we have `div > table:nth-of-type(1) >tr` and `div > table:nth-of-type(2) >tr`  as input and wants to get output like this `div > table > tr`

**Comment by ulshv** [comment]
@iapon I just do `selector.replace(/\:nth-of-type\(\d+\)/g, '')`

**Comment by musabgultekin** [comment]
If anyone interested in browser version: There are 2 of them:
- https://github.com/flatrow/finder/commit/f4fae5fad62bd8598bbbbbd5a4bf81f5ef4018e5
- https://github.com/jerrydeng/finder/commit/6ecf42f6a2354ce4e4678c2e089152f79c2958aa

**Comment by tomgallagher** [comment]
Any idea how I go about getting a js file I can use in the browser from those two links?

**Comment by sabatale** [comment]
@tomgallagher 

`npm install`
`npm run browser`

**Comment by antonmedv** [comment]
Now with v2 will be working!
```js
<script type="module">
  import {finder} from 'https://medv.io/finder/finder.js'
</script>
```
