### ISSUE TITLE
Possibility to set extended CSS selector library

### ISSUE THREAD

**Issue by maZahaca** [antonmedv/finder#20]
Hi there,

I'm using SizzleJs (https://sizzlejs.com) library as extension for my selectors.
Is that possible to extend default `finder` selectors with that?

Thanks

**Comment by antonmedv** [comment]
Hi, what do you mean by extend?

**Comment by maZahaca** [comment]
So, Sizzle provides following improvements on default selectors:

> - CSS 3 Selector support
> - Full Unicode support
> - Escaped selector support #id\:value
> - Contains text :contains(text)
> - Complex :not :not(a#id)
> - Multiple :not :not(div,p)
> - Not attribute value [name!=value]
> - Has selector :has(div)
> - Position selectors :first, :last, :even, :odd, :gt, :lt, :eq
> - Easy Form selectors :input, :text, :checkbox, :file, :password, :submit, :image, :reset, :button
> - Header selector :header

I mean to treat `finder` to generate those extended selectors as well.

**Comment by antonmedv** [comment]
Oh, it's possible. Of cause.

**Comment by maZahaca** [comment]
How? :)

**Comment by antonmedv** [comment]
Implement it in code. I think. :)

**Comment by maZahaca** [comment]
Thanks God this is an option.
