### ISSUE TITLE
Shadow DOM Support

### ISSUE THREAD

**Issue by bennypowers** [antonmedv/finder#27]
Chrome Dev Tools can generate a "JS Path" for an element:

https://developers.google.com/web/updates/2018/11/devtools#copy

It would be great if finder could generate a Chrome Dev Tools-style JS Path for an element, that would be an important step to developing record/replay integration tests for shadow-dom enabled apps.

AFAICT This is a pre-requisite for https://github.com/checkly/puppeteer-recorder/issues/51

**Comment by antonmedv** [comment]
This is interesting. Maybe I'll take a look at this. Or someone whats to make PR?
