### ISSUE TITLE
Provision of js version to download and consume it in html files 

### ISSUE THREAD

**Issue by shivarajnaidu** [antonmedv/finder#28]
Providing js variant to use it in static pages will be helpful to many . please consider including it in repo or some kind of CDN link will be helpful

**Comment by antonmedv** [comment]
Will do later. Now you can use http://unpkg.com/@medv/finder but use `exports`.

**Comment by shivarajnaidu** [comment]
Thank you for the workaround

**Comment by zachdev** [comment]
> Will do later. Now you can use http://unpkg.com/@medv/finder but use `exports`.

This doesn't seem to work due to the `require("cssesc");`.

**Comment by antonmedv** [comment]
Yes you are right

**Comment by sabatale** [comment]
Did you get a chance to do this one?

**Comment by antonmedv** [comment]
Nope. Maybe ES module version will be enough?

**Comment by antonmedv** [comment]
Now with v2 will be working!
```js
<script type="module">
  import {finder} from 'https://medv.io/finder/finder.js'
</script>
```
