### ISSUE TITLE
Support UMD bundles too

### ISSUE THREAD

**Issue by shobhitchittora** [antonmedv/finder#29]
Can we please have a UMD build too? This would help users run this in browser environments as well, using something like `unpkg`.

I tried https://unpkg.com/@medv/finder@1.1.2/dist/index.js and it doesn't work in browsers.

**Comment by antonmedv** [comment]
Now with v2 will be working!
```js
<script type="module">
  import {finder} from 'https://medv.io/finder/finder.js'
</script>
```
