### ISSUE TITLE
Hang on generation

### ISSUE THREAD

**Issue by EugeneVarnavsky** [antonmedv/finder#30]
Generation hangs if you try to generate css selector for <div class="sc-ZUflv kPOZOd">Your location</div> element from the attached HTML file.

[finder_issue.html.txt](https://github.com/antonmedv/finder/files/3978448/finder_issue.html.txt)

**Comment by eggachecat** [comment]
I think this is due to the 「」

**Comment by eggachecat** [comment]
I have been trying to figure out this bug, and I am now pretty sure this happens in 「unique」function when the 「switch」 hist the 「case 0」.
Although the code says it will throw an exception but apparently the 「throw」is not working very well in chrome 「https://stackoverflow.com/questions/28348008/chrome-extension-how-to-trap-handle-content-script-errors-globally」
I hope I can make a PR today..

**Comment by antonmedv** [comment]
Maybe someone can send PR to fix it?

**Comment by eggachecat** [comment]
@antonmedv I am working on this...I think the main reason is the optimizing process does not strict the number of searching and when the selector is deep this will happen..
