### ISSUE TITLE
Site crushes when trying to find large amount of selectors with attributes to exclude

### ISSUE THREAD

**Issue by dbarlev1** [antonmedv/finder#35]
This is occur to me in many sites, when there is large amount of selectors to generate (more the 2000) it crushes.

my conclusion is that it cause by excluding values and names in the attributes.
the new property of "maxNumberOfTries" doesn't help.

Example of my code for the exclude attributes.

excludeByAtributeName=["style", "ng", "on","event"]; 
excludeAttributeValue=["@","?","$","#","~","&","%","^","*","alert","console.log","confirm"];

attr: (name: string, value: string) => 
!excludeByAtributeName
                    .some(a => name.includes(a)) && 
!excludeAttributeValue
                    .some(c => value.includes(c))

**Comment by antonmedv** [comment]
Please attach example html file and what element do you trying generate it for.
