### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by WilliamIPark** [antonmedv/finder#37]
Hey.

First off thank you for creating Finder. It is awesome and it has been the back bone to some awesome features we have on our site.

We are having a small issue with how finder handles errors when it can't find nodes etc, because it throws them. This is a problem because it's picked up by Sentry, and it is creating a lot of noise in our error reporting dashboard.

Would you be open to adding on option for, or changing the error handling so it's a little more graceful? I would personally be happy to write a PR for this if you accept the idea of the improvement. 

Thanks again!

**Comment by antonmedv** [comment]
Cool, if you can describe your idea and use case more detailed it will be nice. Also, PR is welcome.
