### ISSUE TITLE
Duplicate IDs will cause Finder to throw an error and not return a selector

### ISSUE THREAD

**Issue by conormaguire** [antonmedv/finder#40]
Hi there 👋 

I've run into a bug where finder will throw an error if two elements on the same page have the same ID. This is the error being thrown:
https://github.com/antonmedv/finder/blob/1757700b834c3c52937c39af363421f5d45f4998/finder.ts#L69

Very small reproducible example:
```html
<h1 id="duplicate_id">This ID is not unique</h1>
<h1 id="duplicate_id" >This ID is not unique either</h1>
```

Maybe an unoptimized selector could be returned instead here?

**Comment by antonmedv** [comment]
Id in page should be unique. Finder checks it here:  https://github.com/antonmedv/finder/blob/1757700b834c3c52937c39af363421f5d45f4998/finder.ts#L144
And fails. Some workaround for non-uniq id should be implemented. Can somebody try to fix it?

**Comment by antonmedv** [comment]
Fixed! Now works with duplicates!
