### ISSUE TITLE
Is it possible to support custom html elements?

### ISSUE THREAD

**Issue by ashwinvasudevan** [antonmedv/finder#44]
#Offending page
[Link](https://www.amazon.in/Meditations-Penguin-Classics-Marcus-Aurelius/dp/0140449337)

# Offending Element
In the 'Save extra with 4 offers' section, there is a custom  HTML element

<dptags:querylogoperation methodname="addCount" metric="SOPP:sellerPromotionBTF">
..content
</dptags:querylogoperation>

**Comment by Rameshkrishnanb** [comment]
did you got a solution for the above same ?

**Comment by Rameshkrishnanb** [comment]
If yes please do let me know how to crack it!
