### ISSUE TITLE
Ignore dynamic Angular attributes

### ISSUE THREAD

**Issue by alexbonair** [antonmedv/finder#46]
Angular dynamically adds attributes called “_ngcontent-#” to elements by default. 
As those attribute names are regenerated on every load, the **finder** should ignore these attributes while generating css pointers.

**Example Angular 9**
Pointer generated by your tool:
[_ngcontent-**vrx**-c260=“”] > [href=“mailto:hello@example.com”]
after a reload the same elements pointer would need to be:
[_ngcontent-**wok**-c260=“”] > [href=“mailto:hello@example.com”]

Different Angular versions have different ng-content id structures, but it would be fixed by generally ignore all attributes that start with "_ngcontent"

**Comment by antonmedv** [comment]
https://github.com/antonmedv/finder#attr-name-string-value-string--boolean

![](https://imgs.xkcd.com/comics/rtfm.png)

**Comment by alexbonair** [comment]
@antonmedv  Thanks ;)
