### ISSUE TITLE
Finder returns non-unique selector

### ISSUE THREAD

**Issue by vedantroy** [antonmedv/finder#47]
On this page: https://www.buildzoom.com/contractor/live-wire-electric-1-llc

Calling finder on the element returned by this selector: "#credentials > div.team-wrap.row > div:nth-child(2) > div:nth-child(1) > div.biz_info.no-bottom-border.biz-info- > div.bz-content-wrapper > div > table > tbody > tr:nth-child(1) > td.table-item.u-hyphenate"

will make finder return the selector ".table-item", which is non-unique.

**Comment by antonmedv** [comment]
Can you make PR with a falling test for this case?

**Comment by josteph** [comment]
I'll share my finding here just in case. Given an element:

```
<input class="form-control focus-visible" type="text" placeholder="Hello World" required=""  value="">
```

<img width="754" alt="Screen Shot 2022-04-06 at 15 01 13" src="https://user-images.githubusercontent.com/13672022/161927341-d5f9a3bb-7d8d-47c5-bf75-822b5971d753.png">

So in conclusion, it's better to adjust the `seedMinLength` option accordingly.
