### ISSUE TITLE
The execution speed is relatively slow

### ISSUE THREAD

**Issue by 941477276** [antonmedv/finder#56]
When the seedMinLength property is set to 20, the execution speed is very slow, and the browser will be stuck for a while. Can the execution speed be improved?
```
let selector = finder(e.target, {
  className: (name) => {
    return !name.startsWith('is-');
  },
  tagName: (name) => true,
  seedMinLength: 20,
  optimizedMinLength: 15
});
```

**Comment by antonmedv** [comment]
20 seems like a too big starting number. Use 4 or 5.

**Comment by 941477276** [comment]
But sometimes a more accurate CSS selector is needed to accurately locate an element. For example, there are two modal boxes in a Vue single-page application, and both modal boxes have input elements. At this time I need to pinpoint exactly one of the input elements so my css selectors have to be precise enough

**Comment by antonmedv** [comment]
Can you share html page example there I can test it?

**Comment by antonmedv** [comment]
Fixed! Added a cache layer.
