### ISSUE TITLE
CDN Stopped working

### ISSUE THREAD

**Issue by Briuor** [antonmedv/finder#59]
Hello @antonmedv, thank you for the amazing library!
I oppened this issue to let you know that the CDN([https://medv.io/finder/finder.js](https://medv.io/finder/finder.js)) in README.md stopped working.
![image](https://user-images.githubusercontent.com/31521275/170500910-02ff07f1-3fa2-4564-841c-889297faa3d8.png)

For anyone having trouble the alternative CDN link [https://cdn.jsdelivr.net/npm/@medv/finder](https://cdn.jsdelivr.net/npm/@medv/finder) is working.

**Comment by antonmedv** [comment]
Oh) Sorry working on returning it back. I was refactoring my website: medv.io

**Comment by antonmedv** [comment]
Should be back online.

I think I'm gonna create a separate https://cdn.medv.io for this purpose

**Comment by Briuor** [comment]
Thank you man!
