### ISSUE TITLE
Support UMD/global or add usage notes to README

### ISSUE THREAD

**Issue by viveleroi** [antonmedv/finder#6]
Can you please either support UMD/global or add some usage notes to the README? I assume you're expecting users to include this into source via  build pipeline like webpack, but just to play around I tried including it via `script` and it fails with this error:

```
index.js:47 Uncaught ReferenceError: exports is not defined
    at index.js:47
```

Thanks!

**Comment by antonmedv** [comment]
npm install will get builded version. 
Or you can use something like unpkg.com

**Comment by antonmedv** [comment]
I see, maybe you can create dependent package for AMD?
