### ISSUE TITLE
Selector not found

### ISSUE THREAD

**Issue by amol-16** [antonmedv/finder#62]
For some pages -> 
```
  function sort(paths: Iterator<Path> & Iterable<Path>): Path[] {
    return Array.from(paths).sort((a, b) => penalty(a) - penalty(b))
  }
```
Output of "Array.from(paths)" is returning => [ ] (empty array)
Adding a polyfill substitute in this method is solving the issue ->
ex- code

```
function transformToArray <a>(a: Iterator<a>) {
  let result: a[] = []
  let current = a.next()
  while(current.done == false) {
    result.push(current.value)
    current = a.next()
  }
  return result
}

  function sort(paths: Iterator<Path> & Iterable<Path>): Path[] {
    return transformToArray(paths).sort((a, b) => penalty(a) - penalty(b))
  }

```
Let me know, I can raise a PR for the same.

**Comment by antonmedv** [comment]
Yes, let’s go a PR.

**Comment by amol-16** [comment]
@antonmedv PR for above suggested change ->  https://github.com/antonmedv/finder/pull/63

**Comment by antonmedv** [comment]
> For some pages ->

Can you link an example there I can check it?

**Comment by amol-16** [comment]
@antonmedv Example page -> https://www.sanaullastore.com/

**Comment by amol-16** [comment]
added example page and screenshot of error object from library

**Comment by antonmedv** [comment]
Fixed via https://github.com/antonmedv/finder/commit/67eb35c3a36f855d87668b7a65a32b6430842a81
