### ISSUE TITLE
Finder Timeout

### ISSUE THREAD

**Issue by kylevillegas93** [antonmedv/finder#77]
We want to be able to set a timeout on finder.  If we are not able to generate CSS selectors in a certain amount of time, we'd like to return early if the timeout is breached. 

Is this something that could be possible? 

Happy to create a PR and give it a shot as well.

**Comment by antonmedv** [comment]
Nice idea! I think it should be possible.

**Comment by kylevillegas93** [comment]
Awesome thank you @antonmedv. 

Do you have time to review this PR: https://github.com/antonmedv/finder/pull/79 with the change?
